/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dam.di.enoteca.vista;

import dam.di.enoteca.modelo.dto.Botella;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author jose
 */
public class NuevaBotellaJDialog extends javax.swing.JDialog {

    private JTextField campoBodega;
    private JComboBox<String> comboTipo;
    private JComboBox<String> comboUva;
    private JSpinner spinnerAño;
    private JSpinner spinnerPrecio;
    private Botella botellaCreada;
    /**
     * Creates new form NuevaBotellaJDialog
     */
    public NuevaBotellaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaBotellaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaBotellaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaBotellaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaBotellaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaBotellaJDialog dialog = new NuevaBotellaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }



    public NuevaBotellaJDialog(Window parent) {
        super(parent, "Nueva Botella", ModalityType.APPLICATION_MODAL);
        setSize(400, 250);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());

        String[] tipos = { "Joven", "Roble", "Crianza", "Reserva", "Gran Reserva" };
        String[] uvas = { "Merlot", "Cabernet Sauvignon", "Syrah/Shiraz", "Malbec", "Pinot Noir", "Sangiovese", "Nebbiolo", "Garnacha" };

        campoBodega = new JTextField();
        comboTipo = new JComboBox<>(tipos);
        comboUva = new JComboBox<>(uvas);
        spinnerAño = new JSpinner(new SpinnerNumberModel(2025, 1900, 2100, 1));
        spinnerPrecio = new JSpinner(new SpinnerNumberModel(10.0, 0.0, 1000.0, 0.5));

        JPanel panelCampos = new JPanel(new GridLayout(5, 2, 5, 5));
        panelCampos.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Component add = panelCampos.add(new JLabel("Bodega:"));
        panelCampos.add(campoBodega);
        panelCampos.add(new JLabel("Tipo:"));
        panelCampos.add(comboTipo);
        panelCampos.add(new JLabel("Uva:"));
        panelCampos.add(comboUva);
        panelCampos.add(new JLabel("Año:"));
        panelCampos.add(spinnerAño);
        panelCampos.add(new JLabel("Precio (€):"));
        panelCampos.add(spinnerPrecio);

        JPanel panelBotones = new JPanel();
        JButton btnAceptar = new JButton("Aceptar");
        JButton btnCancelar = new JButton("Cancelar");

        btnAceptar.addActionListener(e -> {
            if (campoBodega.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "La bodega no puede estar vacía.");
                return;
            }

            botellaCreada = new Botella(
                    campoBodega.getText().trim(),
                    (String) comboTipo.getSelectedItem(),
                    (String) comboUva.getSelectedItem(),
                    (Integer) spinnerAño.getValue(),
                    (Double) spinnerPrecio.getValue()
            );
            dispose();
        });

        btnCancelar.addActionListener(e -> {
            botellaCreada = null;
            dispose();
        });

        panelBotones.add(btnAceptar);
        panelBotones.add(btnCancelar);

        add(panelCampos, BorderLayout.CENTER);
        add(panelBotones, BorderLayout.SOUTH);
    }

    public Botella getBotellaCreada() {
        return botellaCreada;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

