/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dam.di.enoteca.vista;

import dam.di.enoteca.modelo.dto.Cliente;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author jose
 */
public class NuevoClienteJDialog extends javax.swing.JDialog {
    private JTextField campoNombre;
    private JTextField campoDireccion;
    private JTextField campoCorreo;
    private JTextField campoTelefono;
    private Cliente clienteCreado;
    
    /**
     * Creates new form NuevoClienteJDialog
     * @param parent
     * @param modal
     */
    public NuevoClienteJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, "Nuevo Cliente", true);
        setSize(350, 250);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());

        // Panel de formularios
        JPanel panelFormulario = new JPanel(new GridLayout(4, 2, 5, 5));
        panelFormulario.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        campoNombre = new JTextField();
        campoDireccion = new JTextField();
        campoCorreo = new JTextField();
        campoTelefono = new JTextField();

        panelFormulario.add(new JLabel("Nombre:"));
        panelFormulario.add(campoNombre);
        panelFormulario.add(new JLabel("Dirección:"));
        panelFormulario.add(campoDireccion);
        panelFormulario.add(new JLabel("Correo:"));
        panelFormulario.add(campoCorreo);
        panelFormulario.add(new JLabel("Teléfono:"));
        panelFormulario.add(campoTelefono);

        add(panelFormulario, BorderLayout.CENTER);

        // Botones
        JPanel panelBotones = new JPanel();
        JButton btnAceptar = new JButton("Aceptar");
        JButton btnCancelar = new JButton("Cancelar");

        btnAceptar.addActionListener(e -> {
            if (validarCampos()) {
                clienteCreado = new Cliente(
                        campoNombre.getText().trim(),
                        campoDireccion.getText().trim(),
                        campoCorreo.getText().trim(),
                        campoTelefono.getText().trim()
                );
                dispose();
            }
        });

        btnCancelar.addActionListener(e -> {
            clienteCreado = null;
            dispose();
        });

        panelBotones.add(btnAceptar);
        panelBotones.add(btnCancelar);

        add(panelBotones, BorderLayout.SOUTH);
    }

    private boolean validarCampos() {
        if (campoNombre.getText().isBlank() ||
            campoDireccion.getText().isBlank() ||
            campoCorreo.getText().isBlank() ||
            campoTelefono.getText().isBlank()) {

            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validación muy básica de correo y teléfono (opcionalmente ampliable)
        if (!campoCorreo.getText().contains("@")) {
            JOptionPane.showMessageDialog(this, "Correo no válido.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    public Cliente getClienteCreado() {
        return clienteCreado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
